/* xhcp_transpiler.c (v5.1) — tipos C compuestos (int/unsigned/long/long long/const/*)
   + Literales 0x/0b/0o y exponentes decimales
   + Escapes \xNN en strings
   + Palabras clave: break/continue
   + Soporte "else if (...) :" además de "elif"
   + Mensajes error archivo:línea:columna
   + CLI: -o <out.c>, --dump-tokens, --freestanding/--host
   Mantiene #line y prelude como v5.

   === ABI additions ===
   - --emit-abi ahora genera header con:
       * XHCP_ABI_VERSION, XHCP_API, XHCP_CALL
       * Guards de extern "C"
     y emite prototipos con: XHCP_API <ret> XHCP_CALL <name>(args)
*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <string.h>
#include <ctype.h>
#include <stdarg.h>

/* ---------- Transpiler config flags ---------- */
static int CFG_FREESTANDING = 0;
static int CLI_FREESTANDING = -1; /* -1 unset, 0 host, 1 freestanding */
static const char* g_input_name = "input.xhcp";
static const char* g_output_name = NULL;
static int g_dump_tokens = 0;
/* ---------- ABI emission ---------- */
static const char* g_emit_abi_path = NULL;
typedef struct { char *sig; } AbiItem;
typedef struct { AbiItem* v; int n, cap; } AbiVec;
static AbiVec g_abi;

/* ABI defaults for generated headers (portable) */
#define XHCP_ABI_VERSION_DEFAULT "0x00010000"

static void abi_push(const char* sig){
  if(!sig) return;
  if(g_abi.n==g_abi.cap){
    int nc = g_abi.cap? g_abi.cap*2 : 16;
    AbiItem* nv = (AbiItem*)realloc(g_abi.v, nc*sizeof(AbiItem));
    if(!nv){ perror("realloc abi"); exit(1); }
    g_abi.v=nv; g_abi.cap=nc;
  }
  g_abi.v[g_abi.n++].sig = strdup(sig);
}

static void abi_write_header(const char* path){
  if(!path) return;
  FILE* fo = fopen(path, "wb");
  if(!fo){ perror("fopen --emit-abi"); return; }
  fprintf(fo, "/* Auto-generated by xhcp_transpiler --emit-abi */\n");
  fprintf(fo, "#ifndef XHCP_ABI_H\n#define XHCP_ABI_H\n\n");

  /* extern "C" guards */
  fprintf(fo, "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");

  /* includes + ABI macros */
  fprintf(fo, "#include <stdint.h>\n#include <stddef.h>\n\n");
  fprintf(fo,
    "/* ===== Stable ABI versioning (MAJOR<<16 | MINOR<<8 | PATCH) ===== */\n"
    "#ifndef XHCP_ABI_VERSION\n#define XHCP_ABI_VERSION %s\n#endif\n\n"
    "/* ===== Export / Calling convention macros (platform-portable) ===== */\n"
    "#if defined(_WIN32) || defined(_WIN64)\n"
    "  #ifndef XHCP_API\n"
    "    #define XHCP_API __declspec(dllimport)\n"
    "  #endif\n"
    "  #ifndef XHCP_CALL\n"
    "    #define XHCP_CALL __cdecl\n"
    "  #endif\n"
    "#else\n"
    "  #ifndef XHCP_API\n"
    "    #define XHCP_API\n"
    "  #endif\n"
    "  #ifndef XHCP_CALL\n"
    "    #define XHCP_CALL\n"
    "  #endif\n"
    "#endif\n\n",
    XHCP_ABI_VERSION_DEFAULT
  );

  /* emit prototypes (already have full signature lines) */
  for(int i=0;i<g_abi.n;i++){
    fprintf(fo, "%s;\n", g_abi.v[i].sig);
  }
  fprintf(fo, "\n#ifdef __cplusplus\n}\n#endif\n\n");
  fprintf(fo, "#endif /* XHCP_ABI_H */\n");
  fclose(fo);
}


/* ---------- Fixed types used in generated C ---------- */
typedef   signed char   I8;   typedef unsigned char  U8;
typedef   short         I16;  typedef unsigned short U16;
typedef   int           I32;  typedef unsigned int   U32;
typedef   long long     I64;  typedef unsigned long long U64;
typedef   double        F64;
#define   U0            void

/* ---------- Input ---------- */
typedef struct { const char *data; size_t len, pos; int line, col; } Src;
static char *read_all(const char *path, size_t *out_len){
  FILE *f=fopen(path,"rb"); if(!f){perror("open"); exit(1);}
  if(fseek(f,0,SEEK_END)!=0){perror("fseek"); exit(1);}
  long nl=ftell(f); if(nl<0){perror("ftell"); exit(1);} size_t n=(size_t)nl;
  if(fseek(f,0,SEEK_SET)!=0){perror("fseek"); exit(1);}
  char *buf=(char*)malloc(n+1); if(!buf){fprintf(stderr,"oom\n"); exit(1);}
  size_t rd=fread(buf,1,n,f); fclose(f); if(rd!=n){fprintf(stderr,"short read (%zu/%zu)\n", rd, n); exit(1);}
  buf[n]=0; if(out_len)*out_len=n; return buf;
}

/* ---------- String builder ---------- */
typedef struct { char *buf; size_t n, cap; } Str;
static void sb_init(Str*s){ s->cap=1<<14; s->n=0; s->buf=(char*)malloc(s->cap); s->buf[0]=0; }
static void sb_reserve(Str*s,size_t need){ if(s->n+need+1>s->cap){ s->cap=(s->n+need+1)*2; s->buf=(char*)realloc(s->buf,s->cap);} }
static void sb_puts(Str*s,const char*x){ size_t m=strlen(x); sb_reserve(s,m); memcpy(s->buf+s->n,x,m); s->n+=m; s->buf[s->n]=0; }
static void sb_printf(Str*s,const char*fmt,...){ char tmp[16384]; va_list ap; va_start(ap,fmt); int m=vsnprintf(tmp,sizeof(tmp),fmt,ap); va_end(ap); if(m>0){ sb_reserve(s,(size_t)m); memcpy(s->buf+s->n,tmp,(size_t)m); s->n+=m; s->buf[s->n]=0; }}

/* ---------- Lexer ---------- */
typedef enum {
  T_EOF=0, T_ID, T_NUM, T_STR, T_CHAR, T_NEWLINE, T_COLON, T_COMMA, T_SEMI,
  T_LP, T_RP, T_DOT, T_EQSIGN,
  /* keywords */
  K_U0, K_DEFFUNK, K_DEFUNC, K_END, K_RETURN, K_EXTERN,
  /* control */
  K_IF, K_ELIF, K_ELSE, K_WHILE, K_FOR,
  /* word-operators */
  K_GT, K_LT, K_GE, K_LE, K_EQ, K_NE, K_AND, K_OR, K_NOT,
  /* new control words */
  K_BREAK, K_CONTINUE,
  /* INI */
  K_INI_SEC
} Tok;

typedef struct { Tok kind; char *lex; U64 u64; F64 f64; int line,col; } Token;
static Src S; static Token tk;

static int is_ident1(int c){ return isalpha(c)||c=='_'||c=='$'||c=='@'; }
static int is_ident(int c){ return isalnum(c)||c=='_'||c=='$'||c=='@'; }
static char peek(){ return (S.pos<S.len)? S.data[S.pos] : 0; }
static char getc1(){ if(S.pos>=S.len) return 0; char c=S.data[S.pos++]; if(c=='\n'){S.line++;S.col=1;} else S.col++; return c; }
static void skip_ws(){
  for(;;){
    if(S.pos>=S.len) return;
    char c=S.data[S.pos];
    if(c==' '||c=='\t'||c=='\r'){ S.pos++; S.col++; continue; }
    if(c==';'||c=='#'||(c=='/' && S.pos+1<S.len && S.data[S.pos+1]=='/')){
      while(S.pos<S.len && S.data[S.pos]!='\n') S.pos++;
      continue;
    }
    break;
  }
}
static Token make(Tok k,const char*lex,int l,int c){ Token t={k, lex?strdup(lex):NULL,0,0.0,l,c}; return t; }

static int is_hex(char c){ return (c>='0'&&c<='9')||(c>='a'&&c<='f')||(c>='A'&&c<='F'); }
static int hex_val(char c){ if(c>='0'&&c<='9') return c-'0'; if(c>='a'&&c<='f') return 10+c-'a'; if(c>='A'&&c<='F') return 10+c-'A'; return 0; }

static Token next(){
  skip_ws(); int l=S.line, c=S.col;
  if(S.pos>=S.len) return make(T_EOF,NULL,l,c);
  char ch=getc1();
  if(ch=='\n') return make(T_NEWLINE,NULL,l,c);
  if(ch==':')  return make(T_COLON,":",l,c);
  if(ch==',')  return make(T_COMMA,",",l,c);
  if(ch==';')  return make(T_SEMI,";",l,c);
  if(ch=='(')  return make(T_LP,"(",l,c);
  if(ch==')')  return make(T_RP,")",l,c);
  if(ch=='.')  return make(T_DOT,".",l,c);
  if(ch=='=')  return make(T_EQSIGN,"=",l,c);

  if(ch=='"'){ /* string or "" fmt or "c" for extern "c" */
    if(peek()=='"'){ getc1(); return make(T_STR,"%%FORMAT_FROM_VAR%%",l,c); }
    char buf[1<<14]; int n=0;
    while(S.pos<S.len){
      char d=getc1(); if(d=='"') break;
      if(d=='\\' && S.pos<S.len){
        char e=getc1();
        if(e=='n') buf[n++]='\n';
        else if(e=='t') buf[n++]='\t';
        else if(e=='x'){ /* \xNN */
          int hi = is_hex(peek())? hex_val(getc1()):0;
          int lo = is_hex(peek())? hex_val(getc1()):0;
          buf[n++] = (char)((hi<<4)|lo);
        } else if(e=='"' || e=='\\'){ buf[n++]=e; }
        else { buf[n++]=e; }
      } else buf[n++]=d;
      if(n>=((int)sizeof(buf))-1) break;
    }
    buf[n]=0; return make(T_STR,buf,l,c);
  }
  if(ch=='\''){ /* char or '' expr */
    if(peek()=='\''){ getc1(); return make(T_CHAR,"%%PUTCHAR_EXPR%%",l,c); }
    char v=getc1();
    if(v=='\\'){ char e=getc1(); if(e=='n') v='\n'; else if(e=='t') v='\t'; else if(e=='\''||e=='\\') v=e; }
    if(getc1()!='\''){ fprintf(stderr,"%s:%d:%d: char literal error\n", g_input_name, l, c); }
    char *lex=(char*)malloc(8); lex[0]=v; lex[1]=0; return make(T_CHAR,lex,l,c);
  }
  if(isdigit(ch)){
    /* bases y exponentes */
    char buf[256]; int n=0; buf[n++]=ch;
    if(ch=='0' && (peek()=='x'||peek()=='X'||peek()=='b'||peek()=='B'||peek()=='o'||peek()=='O')){
      char b=getc1(); buf[n++]=b;
      if(b=='x'||b=='X'){ while(is_hex(peek()) && n<255) buf[n++]=getc1(); }
      else if(b=='b'||b=='B'){ while((peek()=='0'||peek()=='1') && n<255) buf[n++]=getc1(); }
      else { while((peek()>='0'&&peek()<='7') && n<255) buf[n++]=getc1(); }
      buf[n]=0; Token t=make(T_NUM,buf,l,c); t.u64=strtoull(buf,NULL,0); t.f64=(F64)t.u64; return t;
    }
    while(isdigit(peek())) buf[n++]=getc1();
    int isfloat=0;
    if(peek()=='.'){ isfloat=1; buf[n++]=getc1(); while(isdigit(peek())) buf[n++]=getc1(); }
    if(peek()=='e'||peek()=='E'){
      isfloat=1; buf[n++]=getc1(); if(peek()=='+'||peek()=='-') buf[n++]=getc1();
      while(isdigit(peek())) buf[n++]=getc1();
    }
    buf[n]=0; Token t=make(T_NUM,buf,l,c);
    if(isfloat){ t.f64=strtod(buf,NULL); }
    else { t.u64=strtoull(buf,NULL,10); t.f64=(F64)t.u64; }
    return t;
  }
  if(ch=='['){
    char buf[256]; int n=0;
    while(S.pos<S.len && S.data[S.pos]!=']' && n<255) buf[n++]=getc1();
    if(peek()==']') getc1();
    buf[n]=0; return make(K_INI_SEC,buf,l,c);
  }
  if(is_ident1(ch)){
    char buf[512]; int n=0; buf[n++]=ch; while(is_ident(peek())) buf[n++]=getc1(); buf[n]=0;
    struct { const char*k; Tok t; } kw[] = {
      {"U0",K_U0},{"deffunk",K_DEFFUNK},{"defunc",K_DEFUNC},{"end",K_END},
      {"return",K_RETURN},{"extern",K_EXTERN},
      {"if",K_IF},{"elif",K_ELIF},{"else",K_ELSE},{"while",K_WHILE},{"for",K_FOR},
      {"greaterthan",K_GT},{"lessthan",K_LT},{"ge",K_GE},{"le",K_LE},
      {"equals",K_EQ},{"notequals",K_NE},{"and",K_AND},{"or",K_OR},{"not",K_NOT},
      {"break",K_BREAK},{"continue",K_CONTINUE},
    };
    for(size_t i=0;i<sizeof(kw)/sizeof(kw[0]);++i) if(strcmp(buf,kw[i].k)==0) return make(kw[i].t,buf,l,c);
    return make(T_ID,buf,l,c);
  }
  if(strchr("+-*/%<>!&|^~[]{}", ch)){
    char buf[3]={ch,0,0}; if((ch=='<'||ch=='>'||ch=='='||ch=='!'||ch=='&'||ch=='|') && peek()=='='){ buf[1]=getc1(); }
    return make(T_ID,buf,l,c);
  }
  char unk[2]={ch,0}; return make(T_ID,unk,l,c);
}

/* ---------- Parser helpers ---------- */
static void need(Tok k){
  if(tk.kind!=k){
    fprintf(stderr,"%s:%d:%d: parse error (need %d, got %d)\n", g_input_name, tk.line, tk.col, k, tk.kind);
    exit(1);
  }
  if(tk.lex) { free(tk.lex); tk.lex=NULL; }
  tk=next();
}
static int accept(Tok k){ if(tk.kind==k){ if(tk.lex){ free(tk.lex); tk.lex=NULL; } tk=next(); return 1;} return 0; }
static const char* opword_to_c(Tok k){
  switch(k){
    case K_GT: return ">"; case K_LT: return "<";
    case K_GE: return ">="; case K_LE: return "<=";
    case K_EQ: return "=="; case K_NE: return "!=";
    case K_AND: return "&&"; case K_OR: return "||"; case K_NOT: return "!";
    default: return NULL;
  }
}

/* ---------- Forward decls ---------- */
static void parse_file(Str*out);
static void parse_header(Str*out);
static void parse_toplevel(Str*out);
static void parse_block(Str*out,int allow_end);
static void parse_stmt(Str*out);
static void parse_if_chain(Str*out);
static void parse_while(Str*out);
static void parse_for(Str*out);

/* ---------- Emit expr token (with op-word mapping) ---------- */
static void emit_expr_token(Str*out){
  const char* sym = opword_to_c(tk.kind);
  if(sym){ sb_puts(out,sym); tk=next(); return; }
  if(tk.kind==T_STR){
    if(strcmp(tk.lex,"%%FORMAT_FROM_VAR%%")==0) { sb_puts(out,"/*FMT_FROM_VAR*/"); tk=next(); return; }
    sb_printf(out,"\"%s\"", tk.lex); tk=next(); return;
  }
  if(tk.kind==T_CHAR){
    if(!strcmp(tk.lex,"%%PUTCHAR_EXPR%%")){ sb_puts(out,"/*PUTCHAR_EXPR*/"); tk=next(); return; }
    sb_printf(out,"'%s'", tk.lex); tk=next(); return;
  }
  if(tk.lex){ sb_printf(out,"%s", tk.lex); tk=next(); return; }
}

/* ---------- Parse (...) generic with op-words ---------- */
static void parse_paren_condition(Str*out){
  need(T_LP);
  sb_puts(out,"(");
  int depth=1;
  while(depth>0 && tk.kind!=T_EOF){
    if(tk.kind==T_LP){ sb_puts(out,"("); tk=next(); depth++; continue; }
    if(tk.kind==T_RP){ sb_puts(out,")"); tk=next(); depth--; if(depth==0) break; else continue; }
    const char* sym=opword_to_c(tk.kind);
    if(sym){ sb_puts(out,sym); tk=next(); }
    else { if(tk.kind==T_STR){ if(strcmp(tk.lex,"%%FORMAT_FROM_VAR%%")==0) sb_puts(out,"/*FMT_FROM_VAR*/"); else sb_printf(out,"\"%s\"", tk.lex); tk=next(); }
           else if(tk.kind==T_CHAR){ if(!strcmp(tk.lex,"%%PUTCHAR_EXPR%%")) sb_puts(out,"/*PUTCHAR_EXPR*/"); else { sb_printf(out,"'%s'", tk.lex); } tk=next(); }
           else { if(tk.lex) sb_printf(out,"%s", tk.lex); tk=next(); } }
    sb_puts(out," ");
  }
}

/* ---------- INI header ---------- */
static void lower(char* s){ for(;*s;++s)*s=(char)tolower((unsigned char)*s); }

static void parse_header(Str*out){
  while(tk.kind==K_INI_SEC){
    char sec[128]; strncpy(sec, tk.lex, sizeof(sec)); sec[sizeof(sec)-1]=0;
    char sec_l[128]; strncpy(sec_l, sec, sizeof(sec_l)); lower(sec_l);
    tk=next();
    while(tk.kind==T_NEWLINE) tk=next();
    while(tk.kind!=T_EOF && tk.kind!=K_INI_SEC && tk.kind!=K_U0 && tk.kind!=K_DEFFUNK && tk.kind!=K_DEFUNC){
      if(tk.kind==T_NEWLINE){ tk=next(); continue; }
      if(!(tk.kind==T_ID && is_ident1(tk.lex[0]))) break;
      char key[256]; strncpy(key, tk.lex, sizeof(key)); tk=next();
      need(T_EQSIGN);
      if(!strcmp(sec_l,"defines")){
        if(tk.kind==T_NUM){ sb_printf(out,"const U64 %s = %lluULL;\n", key, (unsigned long long)tk.u64); tk=next(); }
        else if(tk.kind==T_STR && strcmp(tk.lex,"%%FORMAT_FROM_VAR%%")!=0){ sb_printf(out,"static const char %s[] = \"%s\";\n", key, tk.lex); tk=next(); }
        else if(tk.kind==T_ID){
          if(!strncmp(tk.lex,"0x",2)||!strncmp(tk.lex,"0X",2)){ U64 v=strtoull(tk.lex,NULL,16); sb_printf(out,"const U64 %s = 0x%llxULL;\n", key, (unsigned long long)v); tk=next(); }
          else if(!strcmp(tk.lex,"true")||!strcmp(tk.lex,"false")){ sb_printf(out,"const int %s = %d;\n", key, !strcmp(tk.lex,"true")); tk=next(); }
          else { sb_printf(out,"/* defines %s = %s (unhandled id) */\n", key, tk.lex); tk=next(); }
        } else { sb_printf(out,"/* defines %s (unsupported) */\n", key); }
      } else if(!strcmp(sec_l,"addresses")){
        if(tk.kind==T_ID && (!strncmp(tk.lex,"0x",2)||!strncmp(tk.lex,"0X",2))){
          U64 v=strtoull(tk.lex,NULL,16);
          sb_printf(out,"const U64 %s = 0x%llxULL;\n", key, (unsigned long long)v);
          tk=next();
        } else if(tk.kind==T_NUM){ sb_printf(out,"const U64 %s = %lluULL;\n", key, (unsigned long long)tk.u64); tk=next(); }
        else { sb_printf(out,"/* addresses %s unsupported */\n", key); }
      } else if(!strcmp(sec_l,"switches")){
        if(tk.kind==T_ID){
          char val[256]; strncpy(val, tk.lex, sizeof(val)); lower(val);
          if(!strcmp(key,"FREESTANDING") || !strcmp(key,"freestanding")){
            if(!strcmp(val,"on")||!strcmp(val,"true")||!strcmp(val,"1")) CFG_FREESTANDING=1; else CFG_FREESTANDING=0;
          }
          sb_printf(out,"/* switch %s=%s */\n", key, tk.lex); tk=next();
        } else if(tk.kind==T_NUM){ sb_printf(out,"/* switch %s=%llu */\n", key, (unsigned long long)tk.u64); tk=next(); }
        else if(tk.kind==T_STR){ sb_printf(out,"/* switch %s=\"%s\" */\n", key, tk.lex); tk=next(); }
      } else {
        sb_printf(out,"/* ini section [%s] key %s ignored */\n", sec, key);
      }
      while(tk.kind==T_NEWLINE) tk=next();
    }
    while(tk.kind==T_NEWLINE) tk=next();
  }
}

/* ---------- Signatures / defaults ---------- */
typedef struct { char *type_text; char *name; int has_default; char *default_expr; } Param;
typedef struct { char *name; int returns_value; char *ret_type; Param *params; int nparams; int ndefaults; } FuncSig;
static char* dupstr(const char*s){ return s?strdup(s):NULL; }
static void expect_param_ident(Token t){ if(!(t.kind==T_ID)) { fprintf(stderr,"%s:%d:%d: param expects ident\n", g_input_name, t.line, t.col); exit(1);} }
static const char* opword_to_c(Tok);

/* NUEVO: reconocer modificadores/qualifiers de tipo estilo C */
static int is_type_modifier(const char* s){
  return !strcmp(s,"const") || !strcmp(s,"volatile") || !strcmp(s,"restrict")
      || !strcmp(s,"unsigned") || !strcmp(s,"signed")
      || !strcmp(s,"short") || !strcmp(s,"long")
      || !strcmp(s,"_Atomic") || !strcmp(s,"_Alignas")
      || !strcmp(s,"*"); /* admitimos pegar asterisco como token ID */
}

static void parse_param_list(FuncSig*fs){
  int cap=8; fs->params=(Param*)calloc(cap,sizeof(Param)); fs->nparams=0; fs->ndefaults=0;
  while(tk.kind!=T_RP && tk.kind!=T_EOF){
    if(fs->nparams==cap){ cap*=2; fs->params=(Param*)realloc(fs->params,cap*sizeof(Param)); }
    Param *p=&fs->params[fs->nparams]; memset(p,0,sizeof(*p));
    if(!(tk.kind==T_ID)){ fprintf(stderr,"%s:%d:%d: expected type in param list\n", g_input_name, tk.line, tk.col); exit(1); }
    char typebuf[256]={0}; char namebuf[128]={0};

    /* 1er token del tipo */
    strncat(typebuf, tk.lex, sizeof(typebuf)-1); tk=next();

    /* NUEVO: aceptar calificador/compuesto/asteriscos repetidos */
    while (tk.kind==T_ID && is_type_modifier(tk.lex)) {
      strncat(typebuf," ", sizeof(typebuf)-1);
      strncat(typebuf, tk.lex, sizeof(typebuf)-1);
      tk=next();
    }

    expect_param_ident(tk); strncpy(namebuf, tk.lex, sizeof(namebuf)-1); tk=next();
    p->type_text = strdup(typebuf); p->name=strdup(namebuf); p->has_default=0; p->default_expr=NULL;

    if(accept(T_EQSIGN)){
      Str dex; sb_init(&dex);
      while(tk.kind!=T_COMMA && tk.kind!=T_RP && tk.kind!=T_EOF){
        const char* sym=opword_to_c(tk.kind);
        if(sym){ sb_puts(&dex,sym); tk=next(); }
        else {
          if(tk.kind==T_STR){
            if(strcmp(tk.lex,"%%FORMAT_FROM_VAR%%")==0) sb_puts(&dex,"/*FMT_FROM_VAR*/");
            else { sb_printf(&dex,"\"%s\"", tk.lex); }
            tk=next();
          } else if(tk.kind==T_CHAR){
            if(!strcmp(tk.lex,"%%PUTCHAR_EXPR%%")) sb_puts(&dex,"/*PUTCHAR_EXPR*/");
            else { sb_printf(&dex,"'%s'", tk.lex); }
            tk=next();
          } else {
            if(tk.lex) { sb_puts(&dex, tk.lex); tk=next(); }
          }
        }
        sb_puts(&dex," ");
      }
      p->has_default=1; p->default_expr = strdup(dex.buf); free(dex.buf);
    }
    fs->nparams++;
    if(tk.kind==T_COMMA){ tk=next(); continue; }
    else if(tk.kind==T_RP) break;
  }
}
static void emit_default_overloads(Str*out, const FuncSig*fs){
  int n=fs->nparams; int trailing=0; for(int i=n-1;i>=0;i--){ if(fs->params[i].has_default) trailing++; else break; }
  if(trailing==0) return;
  sb_printf(out, "/* default-arg overloads for %s */\n", fs->name);
  int total = fs->nparams;
  sb_printf(out, "#define XHCP_GET_%s(", fs->name);
  for(int i=1;i<=total;i++) sb_printf(out,"_%d,", i);
  sb_printf(out,"NAME,...) NAME\n");
  sb_printf(out, "#define %s(...) XHCP_GET_%s(", fs->name, fs->name);
  for(int i=1;i<=total;i++) sb_printf(out,"_%d,", i);
  sb_printf(out,"%s__impl,__VA_ARGS__)(__VA_ARGS__)\n", fs->name);
  int min_arity = total - trailing;
  for(int ar=min_arity; ar<total; ++ar){
    sb_printf(out, "static inline %s %s_%d(", fs->returns_value?(fs->ret_type?fs->ret_type:"int"):"U0", fs->name, ar);
    for(int i=0;i<ar;i++){ if(i) sb_puts(out,", "); sb_printf(out,"%s %s", fs->params[i].type_text, fs->params[i].name); }
    sb_puts(out, "){ return "); sb_printf(out, "%s__impl(", fs->name);
    for(int i=0;i<total;i++){ if(i) sb_puts(out,", "); if(i<ar) sb_printf(out,"%s", fs->params[i].name); else sb_printf(out,"%s", fs->params[i].default_expr?fs->params[i].default_expr:"0"); }
    sb_puts(out, "); }\n");
  }
  sb_puts(out,"\n");
}

/* ---------- Control blocks ---------- */
static void parse_if_chain(Str*out){
  need(K_IF);
  parse_paren_condition(out); need(T_COLON);
  sb_puts(out,"if "); sb_puts(out,"{\n");
  parse_block(out,1);
  sb_puts(out,"}");
  /* elif chain */
  while(tk.kind==K_ELIF){
    tk=next(); parse_paren_condition(out); need(T_COLON);
    sb_puts(out," else if "); sb_puts(out,"{\n");
    parse_block(out,1);
    sb_puts(out,"}");
  }
  /* "else if (...):" azúcar */
  if(tk.kind==K_ELSE){
    tk=next();
    if(tk.kind==K_IF){
      tk=next();
      parse_paren_condition(out); need(T_COLON);
      sb_puts(out," else if "); sb_puts(out,"{\n");
      parse_block(out,1);
      sb_puts(out,"}\n");
    } else {
      need(T_COLON);
      sb_puts(out," else {\n"); parse_block(out,1); sb_puts(out,"}");
    }
  }
  sb_puts(out,"\n");
}

static void parse_while(Str*out){
  need(K_WHILE);
  parse_paren_condition(out); need(T_COLON);
  sb_puts(out,"while "); sb_puts(out,"{\n");
  parse_block(out,1);
  sb_puts(out,"}\n");
}

static void parse_for(Str*out){
  need(K_FOR);
  need(T_LP);
  sb_puts(out,"for (");
  int depth=1;
  while(depth>0 && tk.kind!=T_EOF){
    if(tk.kind==T_LP){ sb_puts(out,"("); tk=next(); depth++; continue; }
    if(tk.kind==T_RP){ sb_puts(out,")"); tk=next(); depth--; if(depth==0) break; else continue; }
    const char* sym=opword_to_c(tk.kind);
    if(sym){ sb_puts(out,sym); tk=next(); }
    else { if(tk.kind==T_STR){ if(strcmp(tk.lex,"%%FORMAT_FROM_VAR%%")==0) sb_puts(out,"/*FMT_FROM_VAR*/"); else { sb_printf(out,"\"%s\"", tk.lex);} tk=next(); }
           else if(tk.kind==T_CHAR){ if(!strcmp(tk.lex,"%%PUTCHAR_EXPR%%")) sb_puts(out,"/*PUTCHAR_EXPR*/"); else { sb_printf(out,"'%s'", tk.lex);} tk=next(); }
           else { if(tk.lex) sb_printf(out,"%s", tk.lex); tk=next(); } }
    sb_puts(out," ");
  }
  need(T_COLON);
  sb_puts(out,") {\n");
  parse_block(out,1);
  sb_puts(out,"}\n");
}

static void parse_stmt(Str*out){
  if(tk.kind==K_IF){ parse_if_chain(out); return; }
  if(tk.kind==K_WHILE){ parse_while(out); return; }
  if(tk.kind==K_FOR){ parse_for(out); return; }
  if(tk.kind==K_BREAK){ tk=next(); sb_puts(out,"break;\n"); accept(T_SEMI); while(accept(T_NEWLINE)); return; }
  if(tk.kind==K_CONTINUE){ tk=next(); sb_puts(out,"continue;\n"); accept(T_SEMI); while(accept(T_NEWLINE)); return; }
  if(tk.kind==T_STR){
    if(strcmp(tk.lex,"%%FORMAT_FROM_VAR%%")==0){
      tk=next();
      sb_puts(out,"print(");
      emit_expr_token(out);
      while(accept(T_COMMA)){ sb_puts(out,", "); emit_expr_token(out); }
      sb_puts(out,");\n");
      accept(T_SEMI); while(accept(T_NEWLINE)); return;
    } else {
      /* string literal seguido de ,args => print(fmt,args...) */
      char* fmt = strdup(tk.lex);
      tk = next();
      if(tk.kind==T_COMMA){
        sb_puts(out,"print(\""); sb_puts(out, fmt); sb_puts(out,"\"");
        do { sb_puts(out,", "); tk=next(); emit_expr_token(out); } while(accept(T_COMMA));
        sb_puts(out,");\n");
      } else {
        sb_puts(out,"print(\""); sb_puts(out, fmt); sb_puts(out,"\");\n");
      }
      free(fmt);
      accept(T_SEMI); while(accept(T_NEWLINE)); return;
    }
  }

  if(tk.kind==K_RETURN){
    tk=next();
    sb_puts(out,"return");
    if(!(tk.kind==T_NEWLINE || tk.kind==T_SEMI)) sb_puts(out," ");
    while(tk.kind!=T_NEWLINE && tk.kind!=T_SEMI && tk.kind!=T_EOF){
      const char* sym=opword_to_c(tk.kind);
      if(sym){ sb_puts(out,sym); tk=next(); }
      else { if(tk.lex) sb_printf(out,"%s", tk.lex); tk=next(); }
    }
    if(!accept(T_SEMI)) sb_puts(out,";");
    while(accept(T_NEWLINE));
    sb_puts(out,"\n");
    return;
  }
  while(tk.kind!=T_NEWLINE && tk.kind!=T_SEMI && tk.kind!=T_EOF && tk.kind!=K_END && tk.kind!=K_ELIF && tk.kind!=K_ELSE){
    const char* sym=opword_to_c(tk.kind);
    if(sym){ sb_puts(out,sym); tk=next(); }
    else { if(tk.lex) sb_printf(out,"%s", tk.lex); tk=next(); }
    sb_puts(out," ");
  }
  accept(T_SEMI); accept(T_NEWLINE); sb_puts(out,";\n");
}

static void parse_block(Str*out,int allow_end){
  for(;;){
    while(accept(T_NEWLINE));
    if(allow_end && tk.kind==K_END){ tk=next(); break; }
    if(tk.kind==K_DEFFUNK || tk.kind==K_DEFUNC || tk.kind==K_U0 || tk.kind==T_EOF || tk.kind==K_ELIF || tk.kind==K_ELSE) break;
    parse_stmt(out);
  }
}

/* ---------- extern c / prototypes ---------- */
static void parse_extern(Str*out){
  need(K_EXTERN);
  int is_c_abi=0;
  if(tk.kind==T_STR && tk.lex && strcmp(tk.lex,"c")==0){ is_c_abi=1; tk=next(); }
  else if(tk.kind==T_ID && strcmp(tk.lex,"c")==0){ is_c_abi=1; tk=next(); }
  if(!(tk.kind==T_ID)){ fprintf(stderr,"%s:%d:%d: extern: expected return type\n", g_input_name, tk.line, tk.col); exit(1); }
  char rett[128]; strncpy(rett, tk.lex, sizeof(rett)); tk=next();
  if(!(tk.kind==T_ID)){ fprintf(stderr,"%s:%d:%d: extern: expected function name\n", g_input_name, tk.line, tk.col); exit(1); }
  char name[256]; strncpy(name, tk.lex, sizeof(name)); tk=next();
  need(T_LP);
  Str args; sb_init(&args);
  int first=1;
  while(tk.kind!=T_RP && tk.kind!=T_EOF){
    if(!first) sb_puts(&args,", ");
    if(tk.lex){ sb_puts(&args, tk.lex); tk=next(); }
    if(accept(T_COMMA)){ first=0; continue; }
    first=0;
  }
  need(T_RP);
  accept(T_SEMI); while(accept(T_NEWLINE));

  /* If extern c, collect ABI prototype for separate header */
  Str sig; sb_init(&sig);
  if(is_c_abi){
    /* Signature stored with ABI macros for the generated header */
    sb_printf(&sig, "XHCP_API %s XHCP_CALL %s(%s)", rett, name, args.buf);
    abi_push(sig.buf);
  }

  /* In the generated C unit, keep a normal extern declaration */
  sb_printf(out, "extern %s %s(%s);\n", rett, name, args.buf);

  free(args.buf);
  free(sig.buf);
}


/* ---------- toplevel ---------- */
static void parse_toplevel(Str*out){
  if(tk.kind==K_EXTERN){ parse_extern(out); return; }
  if(tk.kind==K_U0){
    tk=next();
    if(accept(T_COLON)){ sb_puts(out,"int main(void){\n"); parse_block(out,0); sb_puts(out,"return 0;}\n"); return; }
    else {
      if(tk.kind!=T_ID){ fprintf(stderr,"%s:%d:%d: expected name after U0\n", g_input_name, tk.line, tk.col); exit(1); }
      char fname[256]; strncpy(fname, tk.lex, sizeof(fname)); tk=next();
      need(T_LP);
      Str args; sb_init(&args);
      int first=1; while(tk.kind!=T_RP){ if(!first) sb_puts(&args,", "); if(tk.lex){ sb_puts(&args, tk.lex); tk=next(); } if(accept(T_COMMA)){ first=0; continue; } first=0; }
      need(T_RP); need(T_COLON);
      sb_printf(out,"U0 %s(%s){\n", fname, args.buf); free(args.buf);
      parse_block(out,0);
      sb_puts(out,"}\n"); return;
    }
  }
  if(tk.kind==K_DEFFUNK || tk.kind==K_DEFUNC){
    int is_defunc = (tk.kind==K_DEFUNC); tk=next(); need(T_DOT);
    if(tk.kind!=T_ID){ fprintf(stderr,"%s:%d:%d: expected Name after def*.\n", g_input_name, tk.line, tk.col); exit(1); }
    FuncSig fs; memset(&fs,0,sizeof(fs)); fs.name=strdup(tk.lex); fs.returns_value = is_defunc;
    tk=next(); need(T_LP);
    parse_param_list(&fs); need(T_RP);
    if(is_defunc){
      if(tk.kind==T_ID && strcmp(tk.lex,"->")==0){ tk=next(); if(!(tk.kind==T_ID)){ fprintf(stderr,"%s:%d:%d: need return type after ->\n", g_input_name, tk.line, tk.col); exit(1);} fs.ret_type=strdup(tk.lex); tk=next(); }
      else { fs.ret_type=strdup("int"); }
    }
    need(T_COLON);
    emit_default_overloads(out,&fs);
    sb_printf(out,"%s %s__impl(", is_defunc?(fs.ret_type?fs.ret_type:"int"):"U0", fs.name);
    for(int i=0;i<fs.nparams;i++){ if(i) sb_puts(out,", "); sb_printf(out,"%s %s", fs.params[i].type_text, fs.params[i].name); }
    sb_puts(out,"){\n");
    parse_block(out,0);
    sb_puts(out,"}\n");
    if(fs.ndefaults==0){ sb_printf(out,"#ifndef %s\n#define %s(...) %s__impl(__VA_ARGS__)\n#endif\n", fs.name, fs.name, fs.name); }
    for(int i=0;i<fs.nparams;i++){ free(fs.params[i].type_text); free(fs.params[i].name); if(fs.params[i].default_expr) free(fs.params[i].default_expr); }
    free(fs.params); free(fs.name); if(fs.ret_type) free(fs.ret_type);
    return;
  }
  if(tk.kind==T_NEWLINE){ tk=next(); return; }
  sb_puts(out,"int main(void){\n"); parse_block(out,0); sb_puts(out,"return 0;}\n");
}

/* ---------- prelude emission ---------- */
static void emit_prelude(Str*out){
  if(CLI_FREESTANDING!=-1) CFG_FREESTANDING = CLI_FREESTANDING;
  sb_printf(out, "#line 1 \"%s\"\n", g_input_name);
  if(!CFG_FREESTANDING){
    sb_puts(out, "#include \"xhcp_rt.h\"\n");
  } else {
    sb_puts(out,
      "#include <stdint.h>\n"
      "typedef signed char I8; typedef unsigned char U8; typedef short I16; typedef unsigned short U16;\n"
      "typedef int I32; typedef unsigned int U32; typedef long long I64; typedef unsigned long long U64; typedef double F64; typedef void U0;\n"
      "__attribute__((weak)) void xhcp_hw_putc(int c){ (void)c; }\n"
      "__attribute__((weak)) void xhcp_hw_write(const char* s, unsigned long n){ (void)s; (void)n; }\n"
      "static void xhcp_putc(int c){ xhcp_hw_putc(c); }\n"
      "static void xhcp_print(const char*fmt, ...){ (void)fmt; }\n"
      "#define MMIO8(a)  (*(volatile U8*)(a))\n#define MMIO16(a) (*(volatile U16*)(a))\n#define MMIO32(a) (*(volatile U32*)(a))\n#define MMIO64(a) (*(volatile U64*)(a))\n"
      "#if defined(__x86_64__)||defined(__i386__)\n"
      "static inline void outb(U16 port, U8 val){ __asm__ volatile (\"outb %0,%1\"::\"a\"(val),\"Nd\"(port)); }\n"
      "static inline U8 inb(U16 port){ U8 ret; __asm__ volatile (\"inb %1,%0\":\"=a\"(ret):\"Nd\"(port)); return ret; }\n"
      "#endif\n"
    );
  }
}

static void parse_file(Str*out){
  Str header; sb_init(&header);
  parse_header(&header);
  emit_prelude(out);
  sb_puts(out, header.buf);
  free(header.buf);
  while(tk.kind!=T_EOF) parse_toplevel(out);
}

/* ---------- Token dump (opcional) ---------- */
static void dump_all_tokens(const char* in){
  size_t n; char *buf=read_all(in,&n);
  S.data=buf; S.len=n; S.pos=0; S.line=1; S.col=1;
  Token t; do{ t=next(); fprintf(stderr,"[%d:%d] kind=%d lex=%s\n", t.line,t.col, t.kind, t.lex?t.lex:"(nil)"); if(t.lex) free(t.lex); }while(t.kind!=T_EOF);
  free(buf);
}

/* ---------- main ---------- */
int main(int argc,char**argv){
  if(argc<2){ fprintf(stderr,"usage: %s input.xhcp [--freestanding|--host] [-o out.c] [--dump-tokens] [--emit-abi <abi.h>] > out.c\n", argv[0]); return 1; }
  const char* in = NULL;
  for(int i=1;i<argc;i++){
    if(strcmp(argv[i],"--freestanding")==0) CLI_FREESTANDING=1;
    else if(strcmp(argv[i],"--host")==0) CLI_FREESTANDING=0;
    else if(strcmp(argv[i],"--dump-tokens")==0) g_dump_tokens=1;
    else if(strcmp(argv[i],"--emit-abi")==0 && i+1<argc){ g_emit_abi_path = argv[++i]; }
    else if(strcmp(argv[i],"-o")==0 && i+1<argc){ g_output_name = argv[++i]; }
    else in = argv[i];
  }
  if(!in){ fprintf(stderr,"missing input\n"); return 1; }
  g_input_name = in;

  if(g_dump_tokens){ dump_all_tokens(in); }

  size_t n; char *buf=read_all(in, &n);
  S.data=buf; S.len=n; S.pos=0; S.line=1; S.col=1;
  tk=next();
  Str out; sb_init(&out);
  parse_file(&out);

  FILE* fo = stdout;
  if(g_output_name){
    fo = fopen(g_output_name,"wb");
    if(!fo){ perror("fopen -o"); free(out.buf); free(buf); return 1; }
  }
  fwrite(out.buf,1,out.n,fo);
  if(fo!=stdout) fclose(fo);
  free(out.buf); free(buf);
  if(g_emit_abi_path){ abi_write_header(g_emit_abi_path); }
  return 0;
}
